# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-25 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request_service_table',
            fields=[
                ('request_service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('webpage_ref', models.CharField(max_length=18)),
                ('description', models.TextField()),
                ('user_status_is_done', models.BooleanField(default=0)),
                ('dev_status_is_done', models.BooleanField(default=0)),
                ('report_date', models.DateTimeField(auto_now=True)),
                ('service_completion_date', models.DateTimeField()),
            ],
        ),
    ]
