# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_address_table',
            fields=[
                ('customer_address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address_type', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=35)),
                ('country', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='customer_table',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
