# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_address_table',
            options={'verbose_name': "Customer's Address", 'verbose_name_plural': 'Customers Addresses'},
        ),
        migrations.AlterModelOptions(
            name='customer_table',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
