# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-25 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_address_table',
            name='address_type',
            field=models.CharField(choices=[(0, b'Billing'), (1, b'Shipping')], max_length=9),
        ),
        migrations.AlterField(
            model_name='customer_address_table',
            name='country',
            field=models.CharField(choices=[(b'India', b'India')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer_address_table',
            name='state',
            field=models.CharField(choices=[(b'Andhra Pradesh', b'Andhra Pradesh'), (b'Arunachal Pradesh', b'Arunachal Pradesh'), (b'Assam', b'Assam'), (b'Bihar', b'Bihar'), (b'Chattisgarh', b'Chattisgarh'), (b'Goa', b'Goa'), (b'Gujarat', b'Gujarat'), (b'Haryana', b'Haryana'), (b'Himachal Pradesh', b'Himachal Pradesh'), (b'Jammu and Kashmir', b'Jammu and Kashmir'), (b'Jharkhand', b'Jharkhand'), (b'Karnataka', b'Karnataka'), (b'Kerala', b'Kerala'), (b'Madhya Pradesh', b'Madhya Pradesh'), (b'Maharashtra', b'Maharashtra'), (b'Manipur', b'Manipur'), (b'Meghalaya', b'Meghalaya'), (b'Mizoram', b'Mizoram'), (b'Nagaland', b'Nagaland'), (b'Odisha', b'Odisha'), (b'Punjab', b'Punjab'), (b'Rajasthan', b'Rajasthan'), (b'Sikkim', b'Sikkim'), (b'Tamil Nadu', b'Tamil Nadu'), (b'Telangana', b'Telangana'), (b'Tripura', b'Tripura'), (b'Uttar Pradesh', b'Uttar Pradesh'), (b'Uttarakhand', b'Uttarakhand'), (b'West Bengal', b'West Bengal')], max_length=35),
        ),
    ]
