# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_address_table',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
