# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-01 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_registered_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_shop',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
