# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-27 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20190528_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_table',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
