# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-28 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20190528_1005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer_table',
            unique_together=set([('name', 'email')]),
        ),
    ]
