# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-28 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20190528_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_address_table',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer_table'),
        ),
        migrations.AlterField(
            model_name='customer_address_table',
            name='address_type',
            field=models.CharField(choices=[(b'Billing', b'Billing'), (b'Shipping', b'Shipping'), (b'Temporary', b'Temporary')], max_length=9),
        ),
    ]
