# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-29 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20190529_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_address_table',
            name='address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
