# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products_table',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='refill_request_table',
            options={'verbose_name': 'Refill Request', 'verbose_name_plural': 'Refill Requests'},
        ),
        migrations.AlterModelOptions(
            name='stock_entry_table',
            options={'verbose_name': 'Stock Entry', 'verbose_name_plural': 'Stock Entries'},
        ),
        migrations.AlterModelOptions(
            name='stock_table',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
