# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-25 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190525_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill_request_table',
            name='request_status',
            field=models.CharField(choices=[(b'missing', b'missing'), (b'half-done', b'half-done'), (b'fulfilled', b'fulfilled')], max_length=10),
        ),
    ]
