# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190601_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_table',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
