# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-25 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190525_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_table',
            name='cgst_tax',
            field=models.DecimalField(blank=True, choices=[(1, b'0%'), (2, b'5%'), (3, b'12%'), (4, b'18%'), (5, b'28%')], decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='products_table',
            name='igst_tax',
            field=models.DecimalField(blank=True, choices=[(1, b'0%'), (2, b'5%'), (3, b'12%'), (4, b'18%'), (5, b'28%')], decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='products_table',
            name='sgst_tax',
            field=models.DecimalField(blank=True, choices=[(1, b'0%'), (2, b'5%'), (3, b'12%'), (4, b'18%'), (5, b'28%')], decimal_places=2, max_digits=4, null=True),
        ),
    ]
