# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-29 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20190525_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_table',
            name='post_tax_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
