# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-29 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20190529_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_table',
            name='cgst_tax',
            field=models.DecimalField(blank=True, choices=[(0, b'0%'), (5, b'5%'), (12, b'12%'), (18, b'18%'), (28, b'28%')], decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='products_table',
            name='igst_tax',
            field=models.DecimalField(blank=True, choices=[(0, b'0%'), (5, b'5%'), (12, b'12%'), (18, b'18%'), (28, b'28%')], decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='products_table',
            name='sgst_tax',
            field=models.DecimalField(blank=True, choices=[(0, b'0%'), (5, b'5%'), (12, b'12%'), (18, b'18%'), (28, b'28%')], decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
