# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-25 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20190525_2024'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0004_auto_20190525_2135'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_record_table',
            fields=[
                ('delivery_record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=11)),
                ('creation_date', models.DateField(auto_now=True, null=True)),
                ('creation_time', models.TimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[(b'unseen', b'unseen'), (b'reviewed', b'reviewed'), (b'packing', b'packing'), (b'dispatched', b'dispatched'), (b'delivered', b'delivered'), (b'incomplete', b'incomplete'), (b'return', b'return')], default='', max_length=11, null=True)),
                ('customer_address_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer_address_table')),
                ('customer_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer_table')),
                ('employee_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization_table')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mode_of_payment', models.CharField(choices=[(1, b'Cash'), (2, b'Card'), (3, b'E-Waller')], max_length=7)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_table')),
            ],
        ),
        migrations.CreateModel(
            name='product_order_table',
            fields=[
                ('product_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(choices=[(1, b'Cash'), (2, b'Card'), (3, b'E-Waller')])),
                ('post_tax_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('delivery_date', models.DateField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_table')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.products_table')),
            ],
        ),
        migrations.AddField(
            model_name='delivery_record_table',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_table'),
        ),
    ]
