# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-30 04:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('customer', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_record_table',
            fields=[
                ('delivery_record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=11)),
                ('creation_date', models.DateField(auto_now=True)),
                ('creation_time', models.TimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('unseen', 'unseen'), ('reviewed', 'reviewed'), ('packing', 'packing'), ('dispatched', 'dispatched'), ('delivered', 'delivered'), ('incomplete', 'incomplete'), ('return', 'return')], default='', max_length=11, null=True)),
                ('customer_address_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer_address_table')),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer_table')),
                ('employee_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization_table')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('E-Wallet', 'E-Wallet')], default='Cash', max_length=7)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_table')),
            ],
        ),
        migrations.CreateModel(
            name='product_order_table',
            fields=[
                ('product_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('post_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('delivery_date', models.DateField(blank=True, default='', null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_table')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.products_table')),
            ],
        ),
        migrations.AddField(
            model_name='delivery_record_table',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_table'),
        ),
    ]
