# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
        ('customer', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_record_table',
            fields=[
                ('delivery_record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=9)),
                ('creation_date', models.DateField(auto_now=True)),
                ('creation_time', models.TimeField(auto_now=True)),
                ('status', models.CharField(max_length=11)),
                ('customer_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_address_table')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_table')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization_table')),
            ],
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mode_of_payment', models.CharField(max_length=7)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_table')),
            ],
        ),
        migrations.CreateModel(
            name='product_order_table',
            fields=[
                ('product_order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('post_tax_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('delivery_date', models.DateField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_table')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.products_table')),
            ],
        ),
        migrations.AddField(
            model_name='delivery_record_table',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_table'),
        ),
    ]
