# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-26 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order_table',
            name='order_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='order.order_table'),
        ),
    ]
