# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-30 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_table',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
