# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery_record_table',
            options={'verbose_name': 'Delivery Record', 'verbose_name_plural': 'Delivery Records'},
        ),
        migrations.AlterModelOptions(
            name='payment_table',
            options={'verbose_name': 'Checkout', 'verbose_name_plural': 'Checkout'},
        ),
        migrations.AlterModelOptions(
            name='product_order_table',
            options={'verbose_name': 'Product Order', 'verbose_name_plural': 'Product Orders'},
        ),
    ]
