# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-25 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order_table',
            name='post_tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
