# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-25 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table',
            name='random',
            field=models.CharField(default=' ', max_length=10, null=True),
        ),
    ]
