# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190524_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='creation_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='creation_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='customer_address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer_address_table'),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer_table'),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='order_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization_table'),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='status',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
