# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-30 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190530_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_table',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment_table',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
