# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-25 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190526_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order_table',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
