# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-26 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190526_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order_table',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_table'),
        ),
    ]
