# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-25 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190526_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order_table',
            name='quantity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
    ]
