# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-27 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190526_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order_table',
            name='delivery_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
