# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-27 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190527_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order_table',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
