# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-27 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20190527_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order_table',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
