# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-27 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20190527_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization_table'),
        ),
    ]
