# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-29 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20190528_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_table',
            name='mode_of_payment',
            field=models.CharField(choices=[(b'Cash', b'Cash'), (b'Card', b'Card'), (b'E-Wallet', b'E-Waller')], max_length=7),
        ),
    ]
