# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-29 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20190529_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_table',
            name='mode_of_payment',
            field=models.CharField(choices=[(b'Cash', b'Cash'), (b'Card', b'Card'), (b'E-Wallet', b'E-Wallet')], default='Cash', max_length=7),
        ),
    ]
