# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-29 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20190529_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='creation_date',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
