# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-29 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20190529_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_table',
            old_name='creation_date',
            new_name='creat_date',
        ),
    ]
