# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-29 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20190529_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='creat_date',
            field=models.CharField(max_length=20),
        ),
    ]
