# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-29 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20190529_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_table',
            name='creat_date',
        ),
        migrations.AddField(
            model_name='order_table',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
