# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-29 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20190529_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order_table',
            name='delivery_date',
            field=models.DateField(blank=True, default='', max_length=10, null=True),
        ),
    ]
