# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-29 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20190529_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_table',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
