# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 09:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organization_table',
            fields=[
                ('organization_id', models.IntegerField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('whatsappNumber', models.CharField(max_length=10)),
                ('salesEmail', models.EmailField(max_length=254)),
                ('infoEmail', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to=b'')),
                ('addressLine1', models.CharField(max_length=200)),
                ('addressLine2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
            ],
        ),
    ]
