# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-29 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_table',
            name='weblink',
            field=models.URLField(default='www.greenzeeindia.com'),
            preserve_default=False,
        ),
    ]
