# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 09:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_table',
            name='infoEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organization_table',
            name='logo',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='organization_table',
            name='pincode',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
