# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20190524_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_table',
            name='org_code',
            field=models.CharField(default='GI', max_length=3),
            preserve_default=False,
        ),
    ]
