# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_table_org_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_table',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='organization_table',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
