# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-25 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobileNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=35, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('joining_date', models.DateField(auto_now=True, null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('is_user', models.NullBooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('api_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token_created_date', models.DateTimeField(auto_now_add=True)),
                ('organization_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization_table')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='employee_privilege_table',
            fields=[
                ('privilege_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('permissions', models.CharField(max_length=40)),
                ('max_allowed_members', models.IntegerField()),
            ],
            options={
                'verbose_name': "Employee's Privilege",
                'verbose_name_plural': "Employee's Privileges",
            },
        ),
        migrations.AddField(
            model_name='employee_table',
            name='privilege_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee_privilege_table'),
        ),
    ]
