# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-30 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_table',
            options={},
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='api_token',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='is_user',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='mobileNumber',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='privilege_id',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='termination_date',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='token_created_date',
        ),
        migrations.AddField(
            model_name='employee_table',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee_table',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee_table',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name=b'email address'),
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.DeleteModel(
            name='employee_privilege_table',
        ),
    ]
