# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_table',
            name='employee_type',
            field=models.CharField(blank=True, choices=[(b'Administrator', b'Administrator'), (b'Sales Executive', b'Sales Executive'), (b'Intern', b'Intern')], max_length=20, null=True),
        ),
    ]
