# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-25 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_table',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='state',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
