# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-21 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20190521_1310'),
        ('accounts', '0002_auto_20190518_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrators',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
            preserve_default=False,
        ),
    ]
