# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190531_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_table',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_table',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
