# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-22 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190522_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='user',
            name='contactNum',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[(0, b'Intern'), (1, b'General'), (2, b'Manager'), (3, b'Administrator')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
