# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190524_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_privilege_table',
            options={'verbose_name': "Employee's Privilege", 'verbose_name_plural': "Employee's Privileges"},
        ),
        migrations.AlterModelOptions(
            name='employee_table',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
