# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-30 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190530_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_table',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
