# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190524_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_table',
            name='name',
        ),
        migrations.AddField(
            model_name='employee_table',
            name='first_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_table',
            name='last_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
