# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-22 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190522_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[(b'India', b'India')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[(b'Andhra Pradesh', b'Andhra Pradesh'), (b'Arunachal Pradesh', b'Arunachal Pradesh'), (b'Assam', b'Assam'), (b'Bihar', b'Bihar'), (b'Chattisgarh', b'Chattisgarh'), (b'Goa', b'Goa'), (b'Gujarat', b'Gujarat'), (b'Haryana', b'Haryana'), (b'Himachal Pradesh', b'Himachal Pradesh'), (b'Jammu & Kashmir', b'Jammu & Kashmir'), (b'Jharkhand', b'Jharkhand'), (b'Karnataka', b'Karnataka'), (b'Kerala', b'Kerala'), (b'Madhya Pradesh', b'Madhya Pradesh'), (b'Maharashtra', b'Maharashtra'), (b'Manipur', b'Manipur'), (b'Meghalaya', b'Megahalaya'), (b'Mizoram', b'Mizoram'), (b'Nagaland', b'Nagaland'), (b'Odisha', b'Odisha'), (b'Punjab', b'Punjab'), (b'Rajasthan', b'Rajasthan'), (b'Sikkim', b'Sikkim'), (b'Tamil Nadu', b'Tamil Nadu'), (b'Telangana', b'Telangana'), (b'Uttar Pradesh', b'Uttarakhan'), (b'West Bengal', b'West Bengal')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[(b'Intern', b'Intern'), (b'General', b'General'), (b'Manager', b'Manager'), (b'Administrator', b'Administrator')], max_length=15, null=True),
        ),
    ]
