# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190524_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_table',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
