# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_table_mobile_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_table',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='employee_id',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
