# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-21 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190521_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accounter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='user',
        ),
        migrations.DeleteModel(
            name='Accounter',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
